# Document Classifier
## Well, it works 'pretty' well for now.

**load_files** Loads text files with categories as subfolder names. This returns a dictionary-like object

Also **shuffles** the data for us :)

In [1]:
# from sklearn.datasets import fetch_20newsgroups
from sklearn.datasets import load_files

In [2]:
# categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
# all_of_it = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)
all_of_it = load_files("D:\kaam\AdditionalParsed", shuffle=True, random_state = None)

Dividing the training and test data into 80-20 ratio(Roughly).

And show the classes available to us

In [3]:
total = 1772
num = int(0.8*total)
print("No. of Training data: " , num)
print("No. of Testing data: " , total - num)

train_data = all_of_it.data[:num]
test_data = all_of_it.data[num:]

all_of_it.target_names

No. of Training data:  1417
No. of Testing data:  355


['AoI', 'MC']

### Some details about the dataset

In [4]:
print(dir(all_of_it))
print(all_of_it.target_names)
# print(type(all_of_it.description))
print(len(all_of_it.data))
print(all_of_it.target[:10])

['DESCR', 'data', 'filenames', 'target', 'target_names']
['AoI', 'MC']
1772
[1 0 0 1 1 0 1 1 1 0]


#### How the files look like:

In [5]:
all_of_it.filenames[:5]


array(['D:\\kaam\\AdditionalParsed\\MC\\0001064728-17-000026-3.txt',
       'D:\\kaam\\AdditionalParsed\\AoI\\0001552033-15-000013-3.txt',
       'D:\\kaam\\AdditionalParsed\\AoI\\0001193125-15-085094-2.txt',
       'D:\\kaam\\AdditionalParsed\\MC\\0001047469-17-002250-5.txt',
       'D:\\kaam\\AdditionalParsed\\MC\\0001144204-17-016942-7.txt'], 
      dtype='<U56')

### Sample document

In [6]:
print(all_of_it.data[0])

b' htm 469694 Material contracts 10 2017-03-22T05:30:24.667888-05:00 Filing 0001064728-17-000026 2017-03-22 10-K Annual  & Quarterly Reports 0001064728 PEABODY ENERGY CORP BTU NEW COMMON NYSE 1221 Bituminous Coal  & Lignite Surface Mining Yes MISSOURI DELAWARE DELAWARE P &L COAL HOLDINGS CORP false Large Accelerated Filer 001-16463 EXHIBIT 10.127 Exhibit Exhibit 3 btu_20161231xex10127.htm EX-10.127 3 btu_20161231xex10127.htm EXHIBIT 10.127 \n \n \n \n \n \n Exhibit 10.127 \n \n EXECUTION VERSION \n SECOND AMENDMENT TO PRIVATE PLACEMENT AGREEMENT \n THIS SECOND AMENDMENT TO THE PRIVATE PLACEMENT AGREEMENT (this " Amendment"), is made and entered into as February 8, 2017, by and among Peabody Energy Corporation, a Delaware corporation (the " Company ") on behalf of itself and each of its direct and indirect debtor subsidiaries (each a " Debtor " and, collectively, the " Debtors " and, together with their non-Debtor affiliates, the " Company Group") on the one hand, and each Noteholder Co

**CountVectorizer** converts text documents to a matrix representation of token counts.
It takes a list of "strings" as input and creates a matrix

_no. of documents_ *X* _vocabulary_



In [18]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X = count_vect.fit_transform(train_data)

You can take a look at the dimensions of the matrix and the vocabulary that it has created

In [19]:
print(X.shape)
count_vect.vocabulary_

(1417, 46129)


{'htm': 24942,
 '469694': 6809,
 'material': 29269,
 'contracts': 16465,
 '10': 2131,
 '2017': 4268,
 '03': 1677,
 '22t05': 4603,
 '30': 5299,
 '24': 4702,
 '667888': 8104,
 '05': 1799,
 '00': 0,
 'filing': 22354,
 '0001064728': 420,
 '17': 3544,
 '000026': 90,
 '22': 4521,
 'annual': 11590,
 'quarterly': 35120,
 'reports': 36446,
 'peabody': 33238,
 'energy': 20270,
 'corp': 16662,
 'btu': 14151,
 'new': 30968,
 'common': 15804,
 'nyse': 31705,
 '1221': 2702,
 'bituminous': 13666,
 'coal': 15548,
 'lignite': 28347,
 'surface': 40421,
 'mining': 29897,
 'yes': 45059,
 'missouri': 29982,
 'delaware': 17806,
 'holdings': 24785,
 'false': 22011,
 'large': 27827,
 'accelerated': 10192,
 'filer': 22347,
 '001': 1061,
 '16463': 3461,
 'exhibit': 21535,
 '127': 2820,
 'btu_20161231xex10127': 14153,
 'ex': 21147,
 'execution': 21457,
 'version': 43634,
 'second': 38143,
 'amendment': 11325,
 'to': 41567,
 'private': 34456,
 'placement': 33732,
 'agreement': 10891,
 'this': 41297,
 'the': 41164

In [9]:
X.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [3, 5, 0, ..., 0, 0, 0],
       ..., 
       [1, 0, 0, ..., 0, 0, 0],
       [1, 6, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
from sklearn.feature_extraction.text import TfidfTransformer
tf = TfidfTransformer(sublinear_tf=True)
X_train_tf = tf.fit_transform(X)
X_train_tf.shape

(1417, 45837)

In [11]:

X_train_tf.toarray()

array([[ 0.0062977 ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00809362,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01133773,  0.01907747,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.01237914,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01185498,  0.04478767,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01397265,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [12]:
# docs_test = ["God is great", "Retina scan gives early diagnosis about diabetes"]
# X_test = count_vect.transform(docs_test)
# X_tf_test = tf.transform(X_test)

X_test = count_vect.transform(test_data)
X_test_tf = tf.transform(X_test)
X_test_tf.shape

(355, 45837)

In [13]:
# from sklearn.naive_bayes import MultinomialNB
# clf = MultinomialNB()
# clf.fit(X_train_tf,all_of_it.target[:num])

In [14]:
from sklearn import svm
clf = svm.SVC(decision_function_shape="ovo", C = 10000.0, kernel='rbf',gamma = 0.6)
clf.fit(X_train_tf, all_of_it.target[:num])

SVC(C=10000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma=0.6, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
# from sklearn.externals import joblib
# modelfile = "20-news-svm.sav"
# joblib.dump(clf,modelfile)

# loadedmodel = joblib.load(modelfile)

In [16]:

print(clf.score(X_test_tf, all_of_it.target[num:]))
# predict = clf.predict(X_test_tf)
# for text, category in zip(docs_test,predict):
#     print(text + "\tbelongs to:\t" + all_of_it.target_names[category])

0.997183098592


In [17]:
# all_of_it.target_names[int(clf.predict(tf.fit_transform(count_vect.transform(f.read()))))]
HOME_DIR = "D:\kaam\AdditionalParsedTest"
import os
print("File:\tClassification:")
for home,subdir,files in os.walk(HOME_DIR):
    for file in files:
        with open(os.path.join(HOME_DIR, file)) as f:
                print(file + "\t" + all_of_it.target_names[int(clf.predict(tf.transform(count_vect.transform([f.read()]))))])


File:	Classification:
AOI1.txt	AoI
AOI2.txt	AoI
AOI3.txt	AoI
AOI4.txt	AoI
AOI5.txt	AoI
MC1.txt	MC
MC2.txt	MC
MC3.txt	MC
MC4.txt	MC
MC5.txt	MC
