# Document Classifier
## Well, it works 'pretty' well for now.

**load_files** Loads text files with categories as subfolder names. This returns a dictionary-like object

Also **shuffles** the data for us :)

In [1]:
# from sklearn.datasets import fetch_20newsgroups
from sklearn.datasets import load_files

In [17]:
# categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
# all_of_it = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)
all_of_it = load_files("D:\kaam\AdditionalParsed", shuffle=True)

Dividing the training and test data into 80-20 ratio(Roughly).

And show the classes available to us

In [3]:
num = int(0.8*1782)
print("No. of Training data: " , num)
print("No. of Testing data: " , 1782 - num)

train_data = all_of_it.data[:num]
test_data = all_of_it.data[num:]

all_of_it.target_names

No. of Training data:  1425
No. of Testing data:  357


['AoI', 'MC']

### Some details about the dataset

In [4]:
print(dir(all_of_it))
print(all_of_it.target_names)
# print(type(all_of_it.description))
print(len(all_of_it.data))
print(all_of_it.target[:10])

['DESCR', 'data', 'filenames', 'target', 'target_names']
['AoI', 'MC']
1772
[1 0 1 0 1 0 1 0 1 1]


#### How the files look like:

In [5]:
all_of_it.filenames[:5]


array(['D:\\kaam\\AdditionalParsed\\MC\\0001047469-17-001982-5.txt',
       'D:\\kaam\\AdditionalParsed\\AoI\\0001437749-17-004577-2.txt',
       'D:\\kaam\\AdditionalParsed\\MC\\0001614976-17-000010-2.txt',
       'D:\\kaam\\AdditionalParsed\\AoI\\0001144204-16-090060-2.txt',
       'D:\\kaam\\AdditionalParsed\\MC\\0000949428-17-000002-7.txt'], 
      dtype='<U56')

In [6]:
print(all_of_it.data[0])

b' htm 182575 Material contracts 10 2017-03-24T15:30:23.424643-05:00 Filing 0001047469-17-001982 2017-03-24 10-K Annual  & Quarterly Reports 0001260990 GTX INC /DE/ GTXI COMMON Nasdaq Global Market 2834 Pharmaceutical Preparations No TENNESSEE DELAWARE DELAWARE false Accelerated Filer 000-50549 EX-10.7 Exhibit Exhibit 5 a2231118zex-10_7.htm EX-10.7 5 a2231118zex-10_7.htm EX-10.7 \n \n \n Exhibit 10.7 \n   \n GTx, Inc. \n   \n 2002 STOCK OPTION PLAN \n   \n 1.                                         PURPOSE . \n   \n (a)                                   The purpose of the GTx, Inc. 2002 Stock Option Plan (the " Plan") is to provide a means by which selected key employees and directors (if declared eligible under paragraph 4) of and consultants to GTx, Inc. (the " Company"), and its Affiliates, as defined in subparagraph 1(b), may be given an opportunity to benefit from increases in value of the stock of the Company. It is intended that this purpose will be effected through the granting

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X = count_vect.fit_transform(train_data)

In [8]:
print(X.shape)
count_vect.vocabulary_

(1425, 46953)


{'htm': 25505,
 '182575': 3727,
 'material': 30014,
 'contracts': 16912,
 '10': 2148,
 '2017': 4295,
 '03': 1687,
 '24t15': 4842,
 '30': 5372,
 '23': 4662,
 '424643': 6674,
 '05': 1811,
 '00': 0,
 'filing': 22869,
 '0001047469': 397,
 '17': 3580,
 '001982': 1128,
 '24': 4742,
 'annual': 11851,
 'quarterly': 36034,
 'reports': 37381,
 '0001260990': 539,
 'gtx': 24584,
 'inc': 26207,
 'de': 17982,
 'gtxi': 24585,
 'common': 16242,
 'nasdaq': 31465,
 'global': 24224,
 'market': 29914,
 '2834': 5155,
 'pharmaceutical': 34424,
 'preparations': 35164,
 'no': 31979,
 'tennessee': 42014,
 'delaware': 18261,
 'false': 22526,
 'accelerated': 10410,
 'filer': 22863,
 '000': 1,
 '50549': 7214,
 'ex': 21638,
 'exhibit': 22030,
 'a2231118zex': 10183,
 '10_7': 2410,
 '2002': 4113,
 'stock': 40812,
 'option': 33206,
 'plan': 34621,
 'purpose': 35876,
 'the': 42150,
 'of': 32756,
 'is': 27284,
 'to': 42551,
 'provide': 35684,
 'means': 30214,
 'by': 14614,
 'which': 45470,
 'selected': 39233,
 'key': 2

In [9]:
X.toarray()

array([[1, 2, 0, ..., 0, 0, 0],
       [2, 4, 0, ..., 0, 0, 0],
       [1, 3, 0, ..., 0, 0, 0],
       ..., 
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
from sklearn.feature_extraction.text import TfidfTransformer
tf = TfidfTransformer()
X_train_tf = tf.fit_transform(X)
X_train_tf.shape

(1425, 46953)

In [11]:

X_train_tf.toarray()

array([[ 0.00051789,  0.00139509,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00037106,  0.00099956,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00732595,  0.02960206,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.00720659,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00373736,  0.00503387,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00298757,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [12]:
# docs_test = ["God is great", "Retina scan gives early diagnosis about diabetes"]
# X_test = count_vect.transform(docs_test)
# X_tf_test = tf.transform(X_test)

X_test = count_vect.transform(test_data)
X_test_tf = tf.transform(X_test)
X_test_tf.shape

(347, 46953)

In [13]:
# from sklearn.naive_bayes import MultinomialNB
# clf = MultinomialNB()
# clf.fit(X_train_tf,all_of_it.target[:num])

In [14]:
from sklearn import svm
clf = svm.SVC(decision_function_shape="ovo", C = 10000.0, kernel='rbf', gamma = 0.6)
clf.fit(X_train_tf, all_of_it.target[:num])

SVC(C=10000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma=0.6, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
print(clf.score(X_test_tf, all_of_it.target[num:]))
# predict = clf.predict(X_test_tf)
# for text, category in zip(docs_test,predict):
#     print(text + "\tbelongs to:\t" + all_of_it.target_names[category])

0.99711815562


In [16]:
# all_of_it.target_names[int(clf.predict(tf.fit_transform(count_vect.transform(f.read()))))]
HOME_DIR = "D:\kaam\AdditionalParsedTest"
import os
print("File:\tClassified as:")
for home,subdir,files in os.walk(HOME_DIR):
    for file in files:
        with open(os.path.join(HOME_DIR, file)) as f:
                print(file + "\t" + all_of_it.target_names[int(clf.predict(tf.transform(count_vect.transform([f.read()]))))])


File:	Classified as:
AOI1.txt	AoI
AOI2.txt	AoI
AOI3.txt	AoI
AOI4.txt	AoI
AOI5.txt	AoI
MC1.txt	MC
MC2.txt	MC
MC3.txt	MC
MC4.txt	MC
MC5.txt	MC
